### ISSUE TITLE
git push origin ( ) error -fixed-

### ISSUE THREAD

**Issue by jjahoony** [devininy/devininy-Challenge-Guide#1]
I faced an error at command
git push origin ( my branch )

I figured out that I didn't had a git remote repository. so I added repository with command
git remote add origin ( my forked github URL ) 
And checked with command
git remote -v

**Comment by devinan** [comment]
What does my Branch mean?
Is this jjahoony Branch? Or step1..2.3?

**Comment by devinan** [comment]
And you have guides would have been solved, if you saw my homework guide. 
I couldn't find the bug you told me.
you must be a clone your repo that was created by devininy repo fork, you get an remote repository.
